### ISSUE TITLE
arm64 Support

### ISSUE THREAD

**Issue by vavallee** [cablespaghetti/k3s-monitoring#3]
This is awesome.

Sadly the solution doesn't completely work on arm64 as the prometheus-kube-state-metrics doesn't support that architecture. I tried to find some other images that might work, but haven't had any luck. 

Can you point me in the right direction?

**Comment by cablespaghetti** [comment]
Thanks. I haven't tried this on arm64 for a little while but I think kube-state-metrics is probably the last thing left to support multi-arch.

The latest 2.0.0-beta releases seem to be multi-arch now but given the version number change I don't expect it to be a drop in replacement for 1.9.x. One to experiment with maybe.

**Comment by cablespaghetti** [comment]
I've had a look at this tonight. Unfortunately the "args" taken by kube-state-metrics 2.0.0-beta are completely different to 1.9.7 and the old kube-state-metrics Helm chart (https://github.com/helm/charts/tree/master/stable/kube-state-metrics) that the kube-prometheus-stack chart pulls in just can't be made to work with the new version unfortunately.

This works though: https://github.com/prometheus-community/helm-charts/issues/373

I'll make a Pull Request against kube-prometheus-stack to upgrade to the latest Helm Chart so we can try the 2.0.0 branch when I get time.

**Comment by vavallee** [comment]
Thanks so much! Excited to finally have this working.

**Comment by vavallee** [comment]
> I've had a look at this tonight. Unfortunately the "args" taken by kube-state-metrics 2.0.0-beta are completely different to 1.9.7 and the old kube-state-metrics Helm chart (https://github.com/helm/charts/tree/master/stable/kube-state-metrics) that the kube-prometheus-stack chart pulls in just can't be made to work with the new version unfortunately.
> 
> This works though: [prometheus-community/helm-charts#373](https://github.com/prometheus-community/helm-charts/issues/373)
> 
And yes, can confirm that the above works!

**Comment by cablespaghetti** [comment]
Found this unofficial multi-arch image. Going to make this the default in the repo. https://hub.docker.com/r/eddiezane/kube-state-metrics/tags?page=1&ordering=last_updated

Still waiting on kube-state-metrics v2 being stable which has multi-arch builds officially.
